name: Makefile CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: python setup.py develop; make
      
    - name: Run check
      run: make 
